### ISSUE TITLE
code editor error on disabling addon in blender 3.6

### ISSUE THREAD

**Issue by Andrej730** [K-410/blender-scripts#16]
Way to reproduce:
1) Start blender with addon already activated
2) Try to disable it

Traceback:
```
Error: Traceback (most recent call last):
  File "C:\software\Blender_Launcher\daily\blender-3.6.0-beta+daily.58b5d38824de\3.6\scripts\modules\addon_utils.py", line 421, in disable
    mod.unregister()
  File "\Blender\3.6\scripts\addons\code_editor.py", line 1304, in unregister
    set_draw(state=False)
  File "\Blender\3.6\scripts\addons\code_editor.py", line 1227, in set_draw
    st.draw_handler_remove(set_draw._handle, 'WINDOW')
AttributeError: 'function' object has no attribute '_handle'
```

**Comment by Andrej730** [comment]
After this if you don't restart blender you get another error if you try to use text editor:

```
Traceback (most recent call last):
  File "\3.6\scripts\addons\code_editor.py", line 941, in poll
    ce = get_ce(context)
  File "\3.6\scripts\addons\code_editor.py", line 235, in get_ce
    self[handle_id] = handle = CodeEditorMain(context)
  File "\3.6\scripts\addons\code_editor.py", line 981, in __init__
    self.ap = ap = p.addons[__name__].preferences
KeyError: 'bpy_prop_collection[key]: key "code_editor" not found'
```
